## stage 1
FROM node:14-alpine as build

WORKDIR /app

COPY package.json /app

RUN yarn

COPY . /app

RUN yarn build

## stage 2
FROM nginx:stable-alpine

COPY --from=build /app/build /usr/share/nginx/html
#   recuper le stage 1 : le build, et le copie

EXPOSE 80

CMD [ "nginx", "-g", "daemon off;" ]



