version: "3.8"

services: 
  server:
    build: 
      context: .
      dockerfile: ./dockerfiles/nginx.dockerfile
    ports: 
      - '8000:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro # expose ce ficher une fois deployé
      # will merge our config to the already existing conf
    depends_on:
      - php
      - mysql

  php:
    build: 
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated # delegated : improve performence 
        # # # ? # # #
      # - ./src:/var/www/html/storage/logs
      # - ./src:/var/www/html/storage/framework/sessions
      # - ./src:/var/www/html/storage/framework/views
      # - ./src:/var/www/html/storage/framework/cache

  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env

  # Utility container
  composer:
    build: 
      context: ./dockerfiles          # dossier ou se trouve le besoin de build
      dockerfile: composer.dockerfile # fichier source du build
    volumes:
      - ./src:/var/www/html

  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes: 
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]

  npm:
    image: node:14
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes: 
      - ./src:/var/www/html
