version: "3.8"

services:
  mongodb:
    image: 'mongo'
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - data:/data/db

  backend:
    build: ./backend
    container_name: backend
    env_file:
    - ./env/backend.env
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    ports:
      - '80:80'
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - ./frontend/src:/app/src
    ports:
      - '3000:3000'
    depends_on:
      - backend
    # needs an open input connection (react) / interactive mode - optionel ?
    stdin_open: true
    tty: true

volumes:
  data:
  logs: