version: "3.8"

services:
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret

  backend:
    build: ./backend
    env_file:
    - ./env/backend.env
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    ports:
      - '80:80'
    depends_on:
      - mongodb

  #frontend:

volumes:
# les volumes només doivent etre specifiés ici
  data:
  logs: