apiVersion: v1
kind: Service
metadata:
  name: auth-service

spec:
  selector:
    app: auth
  type: ClusterIP # ne sera pas exposer en dehors du cluster
  ports:
  - name: users-service-port
    protocol: TCP
    port: 80
    targetPort: 80
