apiVersion: v1
kind: Service
metadata:
  name: front-service

spec:
  selector:
    app: front
  type: LoadBalancer
  ports:
    - name: front-port
      protocol: TCP
      port: 80
      targetPort: 80
