apiVersion: v1
kind: Service
metadata:
  name: users-service

spec:
  selector:
    app: users
  type: LoadBalancer
  ports:
    - name: users-port
      protocol: TCP
      port: 8080
      targetPort: 8080
