apiVersion: v1
kind: Service
metadata:
  name: users-service

spec:
  selector:
    app: users
  type: LoadBalancer # ClusterIp par default | LoadBalancer : outside world connection
  ports:
  - name: users-service-port
    protocol: TCP
    port: 8080
    targetPort: 8080

