apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv

spec:
  capacity:
    storage: 1Gi
    # https://www.computerweekly.com/feature/Storage-pros-and-cons-Block-vs-file-vs-object-storage
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data
    type: DirectoryOrCreate
