apiVersion: v1
kind: Service
metadata:
  name: story-service
spec:
  selector:
    app: story
  type: LoadBalancer
  ports:
  - name: story-port
    protocol: 'TCP'
    port:  80
    targetPort:  3000